custom:
  - "https://polygonscan.com/address/0x267e548ab3444aa0a671914ac7c644306a6b90b4"
  - "https://tronscan.org/#/address/TWvzvF4FszbXM6qnBS947aNJHfyvA1kdZC"
  - "https://autotest-ai.sweet-possum.workers.dev"
